from app.supabase_client import supabase

def create_user_service(user):
    """
    Adds a new user to Supabase.
    Expects a dict with keys: username, email, password
    Returns a dict with id, username, email
    """
    data = {
        "username": user.get("username"),
        "email": user.get("email"),
        "password": user.get("password")  # store plain text for now
    }
    response = supabase.table("users").insert(data).execute()
    # Return the inserted row (id will be generated by Supabase)
    if response.data:
        inserted = response.data[0]
        return {
            "id": inserted["id"],
            "username": inserted["username"],
            "email": inserted["email"]
        }
    return None

def get_users_service():
    """
    Returns all users from Supabase (excluding passwords)
    """
    response = supabase.table("users").select("*").execute()
    # Remove passwords before returning
    return [
        {"id": u["id"], "username": u["username"], "email": u["email"]}
        for u in response.data
    ] if response.data else []
