def verify_user_service(username, password):
    response = supabase.table("users").select("*").eq("username", username).eq("password", password).execute()
    if response.data:
        user = response.data[0]
        return {
            "id": user["id"],
            "username": user["username"],
            "email": user["email"]
        }
    else:
        return None
from app.supabase_client import supabase

def create_user_service(user):
    """
    Adds a new user to Supabase.
    Expects a dict with keys: username, email, password
    Returns a dict with id, username, email
    """
    data = {
        "username": user.get("username"),
        "hexcolor": user.get("hexcolor"),
        "password": user.get("password")  # store plain text for now
    }
    response = supabase.table("users").insert(data).execute()
    # Return the inserted row (id will be generated by Supabase)
    if response.data:
        inserted = response.data[0]
        return {
            "id": inserted["id"],
            "username": inserted["username"],
            "hexcolor": inserted["hexcolor"]
        }
    return None

def get_users_service():
    """
    Returns all users from Supabase (excluding passwords)
    """
    response = supabase.table("users").select("*").execute()
    # Remove passwords before returning
    return [
        {"id": u["id"], "username": u["username"], "hexcolor": u["hexcolor"]}
        for u in response.data
    ] if response.data else []
